app/models/feeds.py
import requests
import feedparser
import calendar
from time import mktime
from datetime import datetime
from sqlalchemy.exc import IntegrityError
from slugify import slugify

from app import db
from app.models.articles import Article

TYPE_CHOICES = ('culture', 'news', 'politics', 'regional', 'religious')
COUNTRY_CHOICES = ('Croatia', 'Serbia')


class Feed(db.Model):
    '''
    RSS feeds: Parent to articles, classified by TYPE_CHOICES and COUNTRY_CHOICES
    to allow filtering/use of HR or RS dictionaries
    '''
    __tablename__ = 'feeds'

    id = db.Column(db.Integer, primary_key=True)
    articles = db.relationship('Article', backref='feed', lazy='dynamic')
    about = db.Column(db.Text)
    body_tag = db.Column(db.String(250), nullable=False)
    checked = db.Column(db.DateTime)
    country = db.Column(db.Enum(*COUNTRY_CHOICES, name="country"))
    feed_type = db.Column(db.Enum(*TYPE_CHOICES, name="feed_type"))
    logo_filename = db.Column(db.String(250), nullable=True)
    name = db.Column(db.String(250), nullable=False)
    rss = db.Column(db.String(250), unique=True, nullable=False)
    users = db.relationship("Subscription", backref='feeds')
    slug = db.Column(db.String(250), unique=True, nullable=False)
    subscriptions = db.relationship("Subscription", backref='feed')

    def country_choices(self):
        return [(c, c) for c in COUNTRY_CHOICES]

    def type_choices(self):
        return [(c, c) for c in TYPE_CHOICES]

    def __repr__(self):
        return '<Feed: {}>'.format(self.name)

    def update_feed(self, feed):
        '''
        Updates feed content from rss feed, populates articles but not article_text
        Return: feed object
        '''
        try:
            print(feed.rss)
            feed_response = requests.get(feed.rss, headers={'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36'}, timeout=2)
        except Exception as e:
            print(e)
            return False
        if feed_response.status_code == 200:
            posts = feedparser.parse(feed_response.content)
            for p in posts.entries:
                title = p.title
                date = datetime.fromtimestamp(mktime(p.published_parsed))
                url = p.link
                timestamp = calendar.timegm(p.published_parsed)
                slug = "{}_{}_{}".format(feed.id, timestamp, slugify(title))
                if date > feed.checked:
                    new_text = Article(permalink=url,
                                       feed_id=feed.id,
                                       title=title,
                                       date=date,
                                       slug=slug
                                       )
                    try:
                        db.session.add(new_text)
                        db.session.commit()
                    except IntegrityError:
                        ''' Article already exists '''
                        db.session.rollback()
            feed.checked = datetime.now()
            db.session.commit()
            return feed

app/forms/feeds.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, SubmitField, RadioField, TextAreaField
from wtforms.validators import DataRequired, URL

from app import images
from app.models.feeds import Feed


class FeedForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    rss = StringField('RSS feed', validators=[URL()])
    body_tag = StringField('Body Tag', validators=[DataRequired()])
    logo = FileField('Logo', validators=[FileRequired(), FileAllowed(images, 'only images')])
    feed_type = StringField('Feed Type', validators=[DataRequired()])
    country = RadioField(choices=Feed().country_choices())
    feed_type = RadioField(choices=Feed().type_choices())
    about = TextAreaField('About')
    submit = SubmitField('Submit')

app/views/feeds.py
import datetime
from flask import Blueprint, render_template, request, jsonify
from flask_login import current_user, login_required

from app import db
from app.models.feeds import Feed
from app.models.users import Subscription
from app.models.articles import Article

feed_bp = Blueprint('feeds', __name__)


@feed_bp.route('/')
def index():
    feeds = Feed.query.order_by(Feed.name)
    if current_user.is_authenticated:
        subs = Subscription.query.filter_by(user_id=current_user.id).all()
        user_subs = [s.feed_id for s in subs]
    else:
        user_subs = ''
        subs = Subscription.query.all()
    return render_template('feeds/index.html', feeds=feeds, user_subs=user_subs)


@feed_bp.route('/<feed_slug>')
def show(feed_slug):
    f = Feed.query.filter(Feed.slug == feed_slug).first()
    five_hours_ago = datetime.datetime.now() - datetime.timedelta(hours=5)
    if f.checked < five_hours_ago:
        Feed().update_feed(f)
    fa = Article.query.filter(Article.feed_id == f.id).order_by(Article.date.desc())
    return render_template('feeds/show.html', f=f, fa=fa)


@feed_bp.route('/subscriptions/', methods=['GET'])
@login_required
def subscription():
    feed_id = None
    sub_type = None
    if request.method == 'GET':
        feed_id = request.args.get('feed_id', type=int)
        sub_type = request.args.get('sub_type', type=str)
    if feed_id and sub_type:
        fid = Feed.query.get(feed_id)
        uid = current_user.id

        if sub_type == 'sub':
            sub = Subscription(user_id=uid, feed_id=fid.id)
            db.session.add(sub)
            db.session.commit()
            return jsonify('subbed')

        elif sub_type == 'unsub':
            sub = Subscription.query.filter_by(user_id=uid, feed_id=fid.id).first()
            if sub:
                db.session.delete(sub)
                db.session.commit()
                return jsonify('unsubbed')
            else:
                return jsonify('not subbed to this feed')
        else:
            return jsonify('bad formatting')
    else:
        return jsonify('bad formatting')

app/templates/feeds/index.html
{% extends "layouts/base.html" %}
{% block title %}Feeds: {%endblock %}

{% block content %}
  {% for f in feeds %}
		<div class='col-xs-12 feed-list'>
			<div class='col-xs-6 col-sm-2'>
				<a href="{{ url_for('feeds.show', feed_slug=f.slug) }}"><img src="/static/public/uploads/feeds/{{ f.logo_filename }}" /></a>
			</div>
			<div class='col-xs-6 col-sm-10 feed-item'>
				<h3><a href="{{ url_for('feeds.show', feed_slug=f.slug) }}">{{ f.name }}</a></h3>
        {% if current_user.is_authenticated %}
					<span class='subButton btn {% if f.id in user_subs %}subbed{%endif%}' data-feed='{{ f.id }}' data-sub='{% if f.id in user_subs %}unsub{% else %}sub{%endif%}'> + </span>
        {% endif %}
				<p class='about-feed'>{{ f.about }}</p>
			</div>
		</div>
  {% endfor %}
{% endblock %}


{% block extra_js %}
{% assets filters="rjsmin", output="public/js/feeds.js", "js/feeds.js" %}
	<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock %}

app/templates/feeds/new.html
{% extends "layouts/base.html" %}
{% block title %}New Feed: {%endblock %}

{% block content %}
  {% if current_user.is_authenticated and current_user.has_role('admin') %}
    <h1>New Feed</h1>
    <form action="" method="post" name="feed" enctype="multipart/form-data">
      {{ form.csrf_token() }}
      <div class='form-group'>
        {{ form.name(class='form-control', placeholder='name') }}
			  {% for error in form.name.errors %}
				  <span style="color: red;">[{{ error }}]</span>
				{% endfor %}
      </div>
      <div class='form-group'>
        {{ form.body_tag(class='form-control', placeholder='body tag: ex div#article-content') }}
			  {% for error in form.body_tag.errors %}
				  <span style="color: red;">[{{ error }}]</span>
				{% endfor %}
      </div>
      <div class='form-group'>
        {{ form.rss(class='form-control', placeholder='rss') }}
			  {% for error in form.rss.errors %}
				  <span style="color: red;">[{{ error }}]</span>
				{% endfor %}
      </div>
      <div class='form-group'>
        {{ form.logo.name }}
        {{ form.logo(class='form-control', placeholder='logo') }}
			  {% for error in form.logo.errors %}
				  <span style="color: red;">[{{ error }}]</span>
				{% endfor %}
      </div>
      <div class='form-group'>
        {{ form.country.label }}
        {{ form.country }}
			  {% for error in form.country.errors %}
				  <span style="color: red;">[{{ error }}]</span>
				{% endfor %}
      </div>
      <div class='form-group'>
        {{ form.feed_type.label }}
        {{ form.feed_type }}
			  {% for error in form.feed_type.errors %}
				  <span style="color: red;">[{{ error }}]</span>
				{% endfor %}
      </div>
      <div class='form-group'>
        {{ form.about(class='form-control', placeholder='about') }}
			  {% for error in form.about.errors %}
				  <span style="color: red;">[{{ error }}]</span>
				{% endfor %}
      </div>
      <div class='form-group'>
        {{ form.submit(class='btn btn-primary') }}
      </div>
    </form>
  {% endif %}
{% endblock %}


{% block extra_js %}
{% endblock %}

app/templates/feeds/show.html
{% extends "layouts/base.html" %}
{% block title %}Feed: {{ f.name }} : {%endblock %}

{% block content %}
  <div class='col-xs-12'>
    <div class='col-xs-3'>
			<img src="/static/public/uploads/feeds/{{ f.logo_filename }}" />
    </div>
    <div class='col-xs-9'>
      <h1>{{ f.name }}</h1>
      <p>{{ f.country }}</p>
      <p>{{ f.about }}</p>
    </div>
  </div>

<div class='col-xs-12'>
  {% for year, year_group in fa|groupby('date.year')|reverse %}
    {% for month, month_group in year_group|groupby('date.month')|reverse %}
      {% for day, list in month_group|groupby('date.day')|reverse %}
          <ul class='list-unstyled article-list'>
            <li>{{ day }}/{{ month }}/{{ year }}</li>
            {% for a in list %}
              <li><a href='/articles/{{ a.id }}/{{ a.slug }}'>{{ a.title }}</a>
            {% endfor %}
          </ul>
      {% endfor %}
    {% endfor %}
  {% endfor %}
</div>

{% endblock %}


{% block extra_js %}
{% endblock %}