app/models/grammar.py
from app import db
from app.models.words import GENDERS


# Cleaned word models b/c dictionary db is still a mess

GENDER_CHOICES = tuple(GENDERS)


class WordCase(db.Model):
    '''
    Cases: Nominative, accusative, etc.
    '''
    __tablename__ = 'word_cases'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), unique=True, nullable=False)
    table = db.Column(db.Text(), nullable=True)
    body = db.Column(db.Text(), nullable=True)

    def __repr__(self):
        return f'<Case: {self.name}>'


class Verb(db.Model):
    '''
    hr_term, en_term
    '''
    __tablename__ = 'verbs'
    id = db.Column(db.Integer, primary_key=True)
    hr_inf = db.Column(db.String(), unique=True, nullable=False)
    en_inf = db.Column(db.String(), nullable=False)
    pres_3 = db.Column(db.String(), nullable=True)
    past_m = db.Column(db.String(), nullable=True)
    past_f = db.Column(db.String(), nullable=True)

    def __repr__(self):
        return f'<Verb: {self.hr_term} > {self.en_term}>'


class Noun(db.Model):
    '''
    hr_term, en_term, gender, plural, animate
    '''
    __tablename__ = 'nouns'
    id = db.Column(db.Integer, primary_key=True)
    hr_term = db.Column(db.String(), unique=True, nullable=False)
    en_term = db.Column(db.String(), nullable=False)
    gender = db.Column(db.Enum(*GENDER_CHOICES, name="noun_gender"))
    plural = db.Column(db.Boolean())
    animate = db.Column(db.Boolean())

    def __repr__(self):
        return f'<Noun: {self.hr_term} > {self.en_term}>'


class Adjective(db.Model):
    '''
    hr_term, en_term
    '''
    __tablename__ = 'adjectives'
    id = db.Column(db.Integer, primary_key=True)
    hr_term = db.Column(db.String(), unique=True, nullable=False)
    en_term = db.Column(db.String(), nullable=False)

    def __repr__(self):
        return f'<Adjective: {self.hr_term} > {self.en_term}>'


class Adverb(db.Model):
    '''
    hr_term, en_term
    '''
    __tablename__ = 'adverbs'
    id = db.Column(db.Integer, primary_key=True)
    hr_term = db.Column(db.String(), unique=True, nullable=False)
    en_term = db.Column(db.String(), nullable=False)

    def __repr__(self):
        return f'<adverb: {self.hr_term} > {self.en_term}>'


class Preposition(db.Model):
    '''
    hr_term, en_term
    '''
    __tablename__ = 'prepositions'
    id = db.Column(db.Integer, primary_key=True)
    hr_term = db.Column(db.String(), unique=True, nullable=False)
    en_term = db.Column(db.String(), nullable=False)
    description = db.Column(db.String(), nullable=True)

    def __repr__(self):
        return f'<preposition: {self.hr_term} > {self.en_term}>'

app/forms/grammar.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SubmitField, RadioField, SelectField
from wtforms.validators import DataRequired

from app.models.grammar import GENDER_CHOICES


class WordCaseForm(FlaskForm):
    name = StringField('Case name', validators=[DataRequired()])
    table = StringField('Example table')
    submit = SubmitField('Add Case')


class VerbTypeForm(FlaskForm):
    head_verb = StringField('Head Verb', validators=[DataRequired()])
    code = StringField('Code', validators=[DataRequired()])
    submit = SubmitField('Add Verb Type')


class VerbForm(FlaskForm):
    hr_term = StringField('HR word', validators=[DataRequired()])
    en_term = StringField('EN definition', validators=[DataRequired()])
    type_id = SelectField('VerbType', coerce=int)
    submit = SubmitField('Add Verb')


class NounForm(FlaskForm):
    hr_term = StringField('HR word', validators=[DataRequired()])
    en_term = StringField('EN definition', validators=[DataRequired()])
    gender = RadioField(choices=GENDER_CHOICES)
    plural = BooleanField('Plural')
    animate = BooleanField('Animate')
    submit = SubmitField('Add Verb')


class AdjectiveForm(FlaskForm):
    hr_term = StringField('HR word', validators=[DataRequired()])
    en_term = StringField('EN definition', validators=[DataRequired()])
    submit = SubmitField('Add Adjective')


class AdverbForm(FlaskForm):
    hr_term = StringField('HR word', validators=[DataRequired()])
    en_term = StringField('EN definition', validators=[DataRequired()])
    submit = SubmitField('Add Adverb')

app/views/grammar.py
import random
from sqlalchemy.sql.expression import func
from flask import Blueprint, render_template, request, jsonify, escape
from flask_login import login_required, current_user

from app import db
from app.models.grammar import Verb, WordCase, Noun, Adjective, Adverb
from app.models.words import Definition, HrWord, format_glossary, PRONOUNS, VERB_TENSES, GENDERS
from app.models.users import WordBank
from app.utils.verbs import Conjugation

grammar_bp = Blueprint('grammar', __name__)


@grammar_bp.route('/')
def index():
    return render_template('grammar/index.html')


@grammar_bp.route('/list')
@login_required
def listall():
    wcs = WordCase.query.all()
    nouns = Noun.query.all()
    verbs = Verb.query.all()
    adjs = Adjective.query.all()
    advs = Adverb.query.all()
    context = {'wcs': wcs,
               'nouns': nouns,
               'verbs': verbs,
               'adjs': adjs,
               'advs': advs,
               }
    return render_template('grammar/listall.html', context=context)


@grammar_bp.route('/verbs', methods=['GET'])
def verbs():
    load_list = request.args.get('load_list', type=bool)
    if load_list is True:
        verb_query = Definition.query.order_by(func.random()).join(Definition.hr_words, aliased=True).filter(Definition.role_id == 31).limit(20).all()
        verblist = format_glossary(verb_query)
        for v in verblist:
            p = random.choice(PRONOUNS)
            p_code = p['code'] + random.choice(GENDERS) if len(p['code']) == 2 else p['code']
            v['pronoun_word'] = p['word']
            v['pronoun_code'] = p_code
            vt = random.choice(VERB_TENSES)
            # filter out imperative if not 2S, 2P or 1P
            v['verb_tense'] = 'present' if vt == 'imperative' and p_code[:-1] not in ['2S', '2P', '1P'] else vt
        return jsonify(verblist)
    else:
        context = {'pronouns': PRONOUNS,
                   'tenses': VERB_TENSES
                   }
        return render_template('grammar/verbs.html', context=context)


@grammar_bp.route('/verbs/check', methods=['GET'])
def verb_check():
    # check that all args are present
    if set(['answer', 'verb', 'pronoun_code', 'verb_tense', 'hr_id']).issubset(set([k for k in request.args.keys()])):
        answer = escape(request.args.get('answer', type=str))
        verb = escape(request.args.get('verb', type=str))
        pronoun = escape(request.args.get('pronoun_code', type=str))
        tense = escape(request.args.get('verb_tense', type=str))
        hr_id = escape(request.args.get('hr_id', type=int))
        answer_key = Conjugation(verb, pronoun, tense).conjugate()
        grade = 'correct' if answer_key == answer else 'incorrect'
        grade = {'grade': grade,
                 'hr_id': hr_id,
                 'correct_answer': answer_key,
                 'answer': answer,
                 'verb': verb
                 }
        return jsonify(grade)
    else:
        return jsonify("Format error")


# WORDBANK
@grammar_bp.route('/wordbank/add/', methods=['GET'])
@login_required
def insert_wordbank():
    word_id = None
    add_type = False
    if request.method == 'GET':
        word_id = request.args.get('word_id', type=int)
        add_type = request.args.get('add_type', type=str)
    if word_id:
        wid = HrWord.query.get(word_id)
        uid = current_user.id

        if add_type == 'add':
            check_word = WordBank.query.filter_by(user_id=uid, hr_word_id=wid.id).first()
            if check_word:
                return jsonify('Word already in your wordbank: {}'.format(wid.term))
            else:
                wb = WordBank(user_id=uid, hr_word_id=wid.id)
                db.session.add(wb)
                db.session.commit()
                return jsonify('Added: {}'.format(wid.term))

        elif add_type == 'rm':
            wb = WordBank.query.filter_by(user_id=uid, hr_word_id=wid.id).first()
            if wb:
                db.session.delete(wb)
                db.session.commit()
                return jsonify('Removed: {}'.format(wid.term))
            else:
                return jsonify('Word not in your wordbank')
        else:
            return jsonify('Request format error')
    else:
        return jsonify('Request format error')


@grammar_bp.route('/conjugate')
def conj_test():
    verb = random.choice(['spavati', 'bruniti', 'vidjeti', 'kupovati'])
    p = random.choice(PRONOUNS)['code']
    pronoun = p + random.choice(GENDERS) if len(p) == 2 else p
    tense = random.choice(VERB_TENSES)
    v = Conjugation(verb, pronoun, tense).conjugate()
    return render_template('grammar/conjugate.html', v=v)

app/views/practice.py
import random
from sqlalchemy.sql.expression import func
from flask import Blueprint, render_template, request, redirect, jsonify, escape, flash, url_for
from flask_user import login_required, roles_required, current_user

from app import db, csrf
from app.models.practice import Verb, VerbType, WordCase, Noun, Adjective, Adverb
from app.forms.practice import WordCaseForm, VerbTypeForm, VerbForm, NounForm, AdjectiveForm, AdverbForm
from app.models.words import Definition, WordRole, HrWord, EnWord, format_glossary, PRONOUNS, VERB_TENSES, GENDERS
from app.models.users import WordBank
from app.utils.verbs import Conjugation

practice_bp = Blueprint('practice', __name__)

@practice_bp.route('/')
def index():
    return render_template('practice/index.html')

@practice_bp.route('/list')
@login_required
@roles_required('admin')
def listall():
    wcs = WordCase.query.all()
    vts = VerbType.query.all()
    nouns = Noun.query.all()
    verbs = Verb.query.all()
    adjs = Adjective.query.all()
    advs = Adverb.query.all()
    context = {
            'wcs': wcs,
            'vts': vts,
            'nouns': nouns,
            'verbs': verbs,
            'adjs': adjs,
            'advs': advs,
            }
    return render_template('practice/listall.html', context=context)

@practice_bp.route('/verbs', methods=['GET'])
def verbs():
    load_list = request.args.get('load_list', type=bool)
    if load_list == True:
        verb_query = Definition.query.order_by(func.random()).join(Definition.hr_words, aliased=True).filter(Definition.role_id==31).limit(20).all()
        verblist = format_glossary(verb_query)
        for v in verblist:
            p = random.choice(PRONOUNS)
            p_code = p['code']+random.choice(GENDERS) if len(p['code']) == 2 else p['code']
            v['pronoun_word'] = p['word']
            v['pronoun_code'] = p_code
            vt = random.choice(VERB_TENSES)
            # filter out imperative if not 2S, 2P or 1P
            v['verb_tense'] = 'present' if vt == 'imperative' and p_code[:-1] not in ['2S','2P','1P'] else vt
        return jsonify(verblist)
    else:
        context = {
                'pronouns': PRONOUNS,
                'tenses': VERB_TENSES
                }
        return render_template('practice/verbs.html', context=context)

@practice_bp.route('/verbs/check', methods=['GET'])
def verb_check():
    # check that all args are present
    if set(['answer','verb','pronoun_code','verb_tense','hr_id']).issubset(set([k for k in request.args.keys()])):
        answer = escape(request.args.get('answer', type=str))
        verb = escape(request.args.get('verb', type=str))
        pronoun = escape(request.args.get('pronoun_code', type=str))
        tense = escape(request.args.get('verb_tense', type=str))
        hr_id = escape(request.args.get('hr_id', type=int))

        answer_key = Conjugation(verb,pronoun,tense).conjugate()
        grade = 'correct' if answer_key == answer else 'incorrect'

        grade = {
                'grade': grade,
                'hr_id': hr_id,
                'correct_answer': answer_key,
                'answer': answer,
                'verb': verb
                }

        return jsonify(grade)
    else:
        return jsonify("Format error")


# WORDBANK
@practice_bp.route('/wordbank/add/', methods=['GET'])
@login_required
def insert_wordbank():
    word_id = None
    add_type = False
    if request.method == 'GET':
        word_id = request.args.get('word_id', type=int)
        add_type = request.args.get('add_type', type=str)
    if word_id:
        wid = HrWord.query.get(word_id)
        uid = current_user.id

        if add_type == 'add':
            check_word = WordBank.query.filter_by(user_id=uid,hr_word_id=wid.id).first()
            if check_word:
                return jsonify('Word already in your wordbank: {}'.format(wid.term))
            else:
                wb = WordBank(user_id=uid,hr_word_id=wid.id)
                db.session.add(wb)
                db.session.commit()
                return jsonify('Added: {}'.format(wid.term))

        elif add_type == 'rm':
            wb = WordBank.query.filter_by(user_id=uid,hr_word_id=wid.id).first()
            if wb:
                db.session.delete(wb)
                db.session.commit()
                return jsonify('Removed: {}'.format(wid.term))
            else:
                return jsonify('Word not in your wordbank')
        else:
            return jsonify('Request format error')
    else:
        return jsonify('Request format error')


@practice_bp.route('/conjugate')
def conj_test():
    verb = random.choice(['spavati', 'bruniti', 'vidjeti', 'kupovati'])
    p = random.choice(PRONOUNS)['code']
    pronoun = p+random.choice(GENDERS) if len(p) == 2 else p
    tense = random.choice(VERB_TENSES)
    v = Conjugation(verb,pronoun,tense).conjugate()
    return render_template('practice/conjugate.html', v=v)

app/templates/grammar/conjugate.html
{% extends "layouts/base.html" %}

{% block content %}
  {{ v }}
{% endblock %}


{% block extra_js %}
{% endblock %}

app/templates/grammar/index.html
{% extends "layouts/base.html" %}
{% block title %}Words: {%endblock %}

{% block content %}
<a href='{{ url_for('practice.verbs')  }}'>practice verbs</a>
<a href='{{ url_for('practice.new_verb')  }}'>add verbs</a>
<a href='{{ url_for('practice.listall')  }}'>list all practice items</a>
{% endblock %}


{% block extra_js %}
{% endblock %}

app/templates/grammar/verb_type_form.html
{% extends "layouts/base.html" %}
{% block title %}New Verb Type: {%endblock %}
{% import 'shared/_forms.html' as forms %}

{% block content %}
{% block form %}
<section>
  <form action="{{ form_action }}" method="{{ method | d("POST") }}">
    {{ forms.render(form) }}
  </form>
</section>
{% endblock form %}
{% endblock %}

{% block extra_js %}
{% endblock %}

app/templates/grammar/verbs.html
{% extends "layouts/base.html"%}
{% block title %}Verb practice: {%endblock %}

{% block content %}
<div id='verblistContainer' class='col-xs-12 col-md-8'>
  <form>
    <input id='answerBox' name='answer' type='text' id='autocomplete' class='form-control input-lg' placeholder='answer' value=''/>
    <ul class='list-inline' id='char-list'>
      <li class='extraCharacter'>č</li>  
      <li class='extraCharacter'>ć</li>  
      <li class='extraCharacter'>đ</li> 
      <li class='extraCharacter'>š</li>  
      <li class='extraCharacter'>ž</li>
    </ul>
    <input class="btn btn-success" id="answerButton" name="submit" type="submit" value="Answer">
    <input class="btn btn-alert" id="skipButton" name="submit" type="submit" value="Skip">
  </form>
</div>
<div class='col-xs-12 col-sm-4'>
  <h3>correct</h3>
  <ul id='lastWord'  class='correct list-unstyled'></ul>
  <h3>incorrect</h3>
  <ul id='lastWord' class='incorrect list-unstyled'></ul>
</div>
{% endblock %}

{% block extra_js %}
<script>
  $(document).ready(function(){createVerblist();});createVerblist=function(){var listContainer=$('#verblistContainer');var numLeft=$('.verb-list').length;$.getJSON("{{ url_for('practice.verbs') }}",{'load_list':'True'},function(data){$.each(data,function(index,value){if(index===0){activate=' active'}else{activate=''};listContainer.prepend('<ul class=\'list-unstyled verb-list\' data-pron=\''+value.pronoun_code+'\' data-verb=\''+value.hr_word+'\' data-tense=\''+value.verb_tense+'\' data-hr_id=\''+value.def_id+'\'><li class=\'\' id=\''+value.def_id+'\'><h1>'+value.hr_word+'</h1></li><li class=\'definitions\'>'+value.en_words.join(',')+'</li>{% if current_user.is_authenticated and current_user.has_role('admin') %}<li>[<span id=\'notVerb\' class=\'admin-text\'>not a verb/infinitive</span>]</li>{% endif %}<li class=\'challenge\'><h3>'+value.pronoun_word+' + '+value.verb_tense+' ('+value.pronoun_code+') '+'</h3></li></ul>');})
  if(numLeft===0){$('#verblistContainer').find('ul.verb-list').first().addClass('active');}});}
  nextWord=function(){var numLeft=$('.verb-list').length;$('.verb-list.active').remove();if(numLeft===2){createVerblist();}
  $('.verb-list').first().addClass('active');}
  $(document).on('click','#skipButton',function(){event.preventDefault();nextWord();});$(document).on('click','#notVerb',function(){var hr_id=$('.verb-list.active').data('hr_id');$.ajax({type:'POST',url:'{{ url_for('practice.rm_verb_role') }}',data:{'hr_id':hr_id},success:function(data,response){nextWord();}});});$(document).on('submit',function(){event.preventDefault();var pronoun=$('.verb-list.active').data('pron');var verb_tense=$('.verb-list.active').data('tense');var verb=$('.verb-list.active').data('verb');var hr_id=$('.verb-list.active').data('hr_id');var answer=$('#answerBox').val();var numLeft=$('.verb-list').length;$('.verb-list.active').remove();$.getJSON("/practice/verbs/check",{'pronoun_code':pronoun,'verb':verb,'verb_tense':verb_tense,'answer':answer,'hr_id':hr_id},function(data,response){if(data.grade=='correct'){$('#lastWord.correct').prepend('<li><span id=\''+data.hr_id+'\' class=\'hr-term\' data-add=\'add\'>'+data.verb+'</span></li>');}else{$('#lastWord.incorrect').prepend('<li><span id=\''+data.hr_id+'\' class=\'hr-term\' data-add=\'add\'>You:'+data.answer+' Answer:'+data.correct_answer+'</span></li>');}
  $('#answerBox').val('');})
  if(numLeft===2){createVerblist();}
  nextWord();});
</script>
{% endblock %}